# Generated by Django 5.2.8 on 2025-11-17 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del área')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('es_mesa_entrada', models.BooleanField(default=False, help_text='Marca si esta área recibe trámites nuevos de ciudadanos', verbose_name='¿Es Mesa de Entrada?')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Área',
                'verbose_name_plural': 'Áreas',
                'ordering': ['nombre'],
            },
        ),
    ]
